import type { Metadata } from "next";
import { Ribeye_Marrow, Roboto_Mono } from "next/font/google";
import Providers from "./providers";

import "./globals.css";
import { Header } from "@/components/site/Header";

const headerFont = Ribeye_Marrow({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap",
});

const bodyFont = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${headerFont.variable} ${bodyFont.variable} antialiased`}
      >
        {/* React Query Provider */}
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
